//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoteles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoteles()
        {
            this.amenidades = new HashSet<amenidades>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string pais { get; set; }
        public Nullable<decimal> puntuacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amenidades> amenidades { get; set; }
    }
}
