//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoBDEntities : DbContext
    {
        public ProyectoBDEntities()
            : base("name=ProyectoBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amenidades> amenidades { get; set; }
        public virtual DbSet<carros> carros { get; set; }
        public virtual DbSet<destino> destino { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<hoteles> hoteles { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<resennas> resennas { get; set; }
        public virtual DbSet<reservaCarros> reservaCarros { get; set; }
        public virtual DbSet<reservaHoteles> reservaHoteles { get; set; }
        public virtual DbSet<reservaTours> reservaTours { get; set; }
        public virtual DbSet<reservaVuelos> reservaVuelos { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<tours> tours { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<vuelos> vuelos { get; set; }
    }
}
