//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoBDEntities : DbContext
    {
        public ProyectoBDEntities()
            : base("name=ProyectoBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amenidades> amenidades { get; set; }
        public virtual DbSet<carro> carro { get; set; }
        public virtual DbSet<destino> destino { get; set; }
        public virtual DbSet<hoteles> hoteles { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<reservaCarro> reservaCarro { get; set; }
        public virtual DbSet<reservaHotel> reservaHotel { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
