//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservaTours
    {
        public long ID { get; set; }
        public long IdTours { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tours tours { get; set; }
    }
}
