//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.reservaCarro = new HashSet<reservaCarro>();
            this.reservaHotel = new HashSet<reservaHotel>();
        }
    
        public int ID { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDDestino { get; set; }
        public Nullable<System.DateTime> salida { get; set; }
        public Nullable<System.DateTime> entrada { get; set; }
    
        public virtual destino destino { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservaCarro> reservaCarro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservaHotel> reservaHotel { get; set; }
    }
}
