//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservaHotel
    {
        public long IDHotel { get; set; }
        public long IDReserva { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
