//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.reservaCarro = new HashSet<reservaCarro>();
            this.reservaHotel = new HashSet<reservaHotel>();
        }
    
        public long ID { get; set; }
        public int TIPO { get; set; }
        public long IDUser { get; set; }
        public long IDDestino { get; set; }
        public System.DateTime salida { get; set; }
        public System.DateTime entrada { get; set; }
    
        public virtual destino destino { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservaCarro> reservaCarro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservaHotel> reservaHotel { get; set; }
    }
}
