//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class resennas
    {
        public long ID { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public decimal puntuacion { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<long> IdHotel { get; set; }
    
        public virtual hoteles hoteles { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
