//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservaHoteles
    {
        public long ID { get; set; }
        public long IdHotel { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual hoteles hoteles { get; set; }
    }
}
