//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class resennas
    {
        public long ID { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public decimal puntuacion { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<long> IdHotel { get; set; }
    
        public virtual hoteles hoteles { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
